version: "3.8"  # Adjust the version if needed

services:
  rails:
    build: .
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 of the host
    volumes:
      - ./:/usr/src/app  # Mount the project directory for code changes
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/my_rails_app_development
  postgres:
    image: postgres:14-alpine  # Use a specific PostgreSQL version if necessary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Set a strong password for production use
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres-data:  # Named volume for persistent PostgreSQL data
